# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:14
from __future__ import unicode_literals

import ckeditor.fields
import common.utils
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', sorl.thumbnail.fields.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/thumbnails/', location='/vagrant/public/media/thumbnails'), upload_to=common.utils.image_path, verbose_name='category_img')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time stamp')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('visible', models.BooleanField(default=False, verbose_name='is visible')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('user_name', models.CharField(max_length=100, verbose_name='author')),
                ('avatar', sorl.thumbnail.fields.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/avatars/', location='/vagrant/public/media/avatars'), upload_to=common.utils.image_path, verbose_name='avatar')),
                ('short_description', models.CharField(max_length=200, verbose_name='short description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('thumbnail', sorl.thumbnail.fields.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/thumbnails/', location='/vagrant/public/media/thumbnails'), upload_to=common.utils.image_path, verbose_name='thumbnail')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time stamp')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Category', verbose_name='category')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='post'),
        ),
    ]
